INPUT:
  MIN_DIM: 352
  MAX_DIM: 608
  NUM_CLASSES: 2
  NUM_FRAMES: 16
MODEL:
  EMBEDDING_DIM_MODE: "xyff"
  USE_SEEDINESS_HEAD: true
  USE_SEMSEG_HEAD: false
  BACKBONE:
    TYPE: "MULTI-FUSION"
  RESNETS:
    STEM_IN_CHANNELS: 4 # RGB + positive
  EMBEDDINGS:
    EMBEDDING_SIZE: 4
  SEEDINESS:
    HEAD_TYPE: fusion_decoder
TRAINING:
  MODE: "davis"
  FREEZE_BACKBONE: true
  OPTIMIZER: "adam"
  INITIAL_LR: 0.0005
  LR_DECAY_TYPE: "none"
  MAX_ITERATIONS: 20000
  LOSSES:
    EMBEDDING:
      FREE_DIM_STDS: [0.3, 0.3]
DATA:
  YOUTUBE_VIS:
    FRAME_GAP_LOWER: 16
    FRAME_GAP_UPPER: 16