INPUT:
  MIN_DIM: 352
  MAX_DIM: 608
  NUM_CLASSES: 2
  NUM_FRAMES: 8
MODEL:
  EMBEDDING_DIM_MODE: "xyff"
  USE_SEEDINESS_HEAD: true
  USE_SEMSEG_HEAD: false
  BACKBONE:
    TYPE: "MULTI-FUSION"
    FREEZE_AT_STAGE: -1 # Don't freeze
  RESNETS:
    STEM_IN_CHANNELS: 4 # RGB + positive
  EMBEDDINGS:
    EMBEDDING_SIZE: 4
TRAINING:
  MODE: "davis"
  BATCH_SIZE: 4
  OPTIMIZER: "adam"
  INITIAL_LR: 0.00001
  LR_DECAY_TYPE: "exponential"
  LR_EXP_DECAY_FACTOR: 0.1
  LR_EXP_DECAY_START: 40000
  LR_EXP_DECAY_STEPS: 10000
  MAX_ITERATIONS: 80000
  ACCUMULATE_GRADIENTS: False
  MAX_SAMPLES_PER_GPU: 4
  LOSSES:
    EMBEDDING:
      FREE_DIM_STDS: [0.3, 0.3]